version: '3'
services:
  {serviceName}:
    image: {imageName}
    hostname: {hostname}
    container_name: {serviceName}
    restart: always
    ports:
     - {serverPort}:{dockerPort}
    ulimits:
      nofile:
        soft: 65536
        hard: 65536
    security_opt:
      - seccomp:unconfined
    environment:
      EXPORTER_ENABLE: "{exporter_enable}"
      MYSQL_ROOT_PASSWORD: "{mysql_root_password}"
      MYSQLD_EXPORTER_ENABLE: "{mysqld_exporter_enable}"
      NODE_EXPORTER_PATH: "{node_exporter_path}"
      BAILI_XCENTER_SERVER: "{baili_xcenter_server}"
      BAILI_XCENTER_ORGCODE: "{baili_xcenter_orgcode}"
      BAILI_APPLICATION_SERVER: "{baili_application_server}"
      BAILI_COLLECTOR_SERVER: "{baili_collector_server}"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./conf/mysql.cnf:/etc/mysql/conf.d/mysql.cnf
      - ./data/mysql:/var/lib/mysql
      - ./nodeExport:/nodeExport
# 采用网络模式时可配合ports使用，testOps部署后默认名为testOps_network_default，可通过接口参数修改
networks:
  default:
    external:
      name: testOps_network_default