version: '3'
services:
  {serviceName}:
    image: {imageName}
    container_name: {serviceName}
    restart: always
    ports:
      - {serverPort}:{dockerPort}
      - {webPort}:{webdockerPort}
    environment:
      #Kafka启动报异常InconsistentClusterIdException解决方案：https://www.codenong.com/cs110545325/
      EXPORTER_ENABLE: "{exporter_enable}"
      NODE_EXPORTER_PATH: "{node_exporter_path}"
      BAILI_XCENTER_SERVER: "{baili_xcenter_server}"
      BAILI_XCENTER_ORGCODE: "{baili_xcenter_orgcode}"
      BAILI_APPLICATION_SERVER: "{baili_application_server}"
      BAILI_COLLECTOR_SERVER: "{baili_collector_server}"
      RABBITMQ_USERNAME: "{rabbitmq_username}"
      RABBITMQ_PASSWORD: "{rabbitmq_password}"
      RABBITMQ_PID_FILE: "/var/lib/rabbitmq/mnesia/pid.pid"
    volumes:
      - /etc/localtime:/etc/localtime
      - ./data/rabbitmq:/bitnami/rabbitmq/mnesia
      - ./nodeExport:/nodeExport
# 采用网络模式时可配合ports使用，testOps部署后默认名为testOps_network_default，可通过接口参数修改
networks:
  default:
    external:
      name: testOps_network_default